name: PyPi-Release

on:
  push:
    branches:
      - master

jobs:
  pypi-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"
      - name: Install build dependencies
        run: pip install -U setuptools wheel build GitPython
      - name: Build
        run: python -m build .
      - name: Publish
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
      - name: Install Updated PyPI Package
        run: pip install -U cumason-helloworld-package
      - name: Create Tag
        run: python pypi_packaging.py
